server:
  port: 8090
spring:
  data:
    mongodb:
      username: sam
      password: sam
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin